#!/usr/bin/env bash
# displays the content of the file /etc/passwd, using the while loop + IFS.
IFS=':'
while read -r username password uid gid userinfo homedir shell; do
    echo "the user $username is part of the $gid gang, lives in $homedir and rides $shell. $uid's place is protected by the passcode $password, more info about the user here: $userinfo"
done < "/etc/passwd"
