#!/usr/bin/env bash
#displays 8 times "Best School"; 1 time "bad luck" and "good luck"
count=1
while [ $count -lt 11 ]
do
  if [ $count -eq 4 ]
  then
    echo "bad luck"
  elif [ $count -eq 8 ]
  then
    echo "good luck"
  else
  echo "Best School"
  (( count++ ))
  fi
done
