#!/usr/bin/env bash
#this script gives you information about the school file.

if [ -e "school" ]
then
    echo "school file exists"
    if [ -s "school" ]
       echo "school file is not empty"
       else
	   echo "school file is empty"
    fi
   
	   if [ -f "school" ]
	      echo "schoolis a regular file"
	      else
		  echo "(nothing)"
      fi
	      else
		  echo "school file does not exist"
		  fi
done


		
