#!/usr/bin/env bash
#Creates the file /var/run/myscript.pid containing its PID
#Displays To infinity and beyond indefinitely
#Displays I hate the kill command when receiving a SIGTERM signal
#Displays Y U no love me?! when receiving a SIGINT signal
#Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal
echo 'ps myscript.pid' > /var/run/myscript.pid
trap 'echo "I hate the kill command"' SIGTERM
trap 'echo "Y U no love me?!"' SIGINIT
term_handler () {
	echo "I hate the kill command"
	rm -f /var/run/myscript.pid
	exit
}
quit_handler () {
	echo "Y U no love me?!"
	m -f /var/run/myscript.pid
	exit
}
trap term_handler SIGTERM
trap quit_handler SIGQUIT
while true; do
echo "To infinity and beyond"
sleep 2
done

