#!/usr/bin/env bash
#!/usr/bin/env bash
#When passing the argument start:Starts manage_my_process,Creates a file containing its PID in /var/run/my_process.pid,Displays manage_my_process started
#When passing the argument stop:Stops manage_my_process,Deletes the file /var/run/my_process.pid,Displays manage_my_process stopped
#When passing the argument restart:Stops manage_my_process,Deletes the file /var/run/my_process.pid,Starts manage_my_process,Creates a file containing its PID in /var/run/my_process.pid
#Displays manage_my_process restarted
#Displays Usage: manage_my_process {start|stop|restart} if any other argument or no argument is passed
#!/bin/bash

PID_FILE="/var/run/my_process.pid"
PROCESS_SCRIPT="./manage_my_process"
start() {
	$PROCESS_SCRIPT &
	echo $! > $PID_FILE
echo "manage_my_process started"
}

stop() {
if [ -f "$PID_FILE" ]; then
	kill $(cat $PID_FILE)
rm -f $PID_FILE
echo "manage_my_process stopped"
else
echo "manage_my_process is not running"
fi
}

restart() {
	if [ -f "$PID_FILE" ]; then
        kill $(cat $PID_FILE)
rm -f $PID_FILE
	fi
 $PROCESS_SCRIPT &
        echo $! > $PID_FILE
echo "manage_my_process restarted"
}

case "$1" in
start)
start
;;
stop)
stop
;;
restart)
restart
;;
*)
echo "Usage: $0 {start|stop|restart}"
exit 1
;;
esac
