#!/usr/bin/env bash
#displays:To infinity and beyond indefinitely,With a sleep 2 in between each iteration,I am invincible!!! when receiving a SIGTERM signal
x=$(pkill -f 7-highlander)
while true, do
if ($x) 
then
echo "I am invincible!!!"
else
echo "To infinity and beyond"
fi
sleep 2
done
